-- ═══════════════════════════════════════════════════════════════════
-- Migration: 018_group_simulations.sql
-- Description: Create table for storing group simulations and predict results,
--              setup GIN indexes for array searching, extend users table with
--              is_super_admin role flags, and deploy optimized RLS policy.
-- ═══════════════════════════════════════════════════════════════════

-- 1. Create table for group simulations and manager forecast logs
CREATE TABLE IF NOT EXISTS group_simulations (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id              UUID REFERENCES organizations(id) ON DELETE CASCADE,
  leader_id           TEXT NOT NULL,
  selected_user_ids   TEXT[] NOT NULL, -- Array of member user IDs inside simulated group
  project_type        TEXT NOT NULL, -- innovation, execution, crisis_management, cohesion, rov, combat
  calculated_synergy  FLOAT NOT NULL, -- Synergy score (15% - 100%)
  friction_risk_level TEXT NOT NULL DEFAULT 'GREEN', -- GREEN, YELLOW, ORANGE, RED based on friction indexes
  bot_recommendation  TEXT, -- Management guidelines and tips generated by bot
  created_at          TIMESTAMPTZ DEFAULT now()
);

-- 2. Create GIN index for fast array searching in selected_user_ids
CREATE INDEX IF NOT EXISTS idx_group_simulations_users_gin ON group_simulations USING gin (selected_user_ids);

-- 3. Create index for org_id and leader_id searches
CREATE INDEX IF NOT EXISTS idx_group_simulations_org_leader ON group_simulations (org_id, leader_id);

-- 4. Extend users table with is_super_admin column
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_super_admin BOOLEAN DEFAULT false;

-- 5. Seed whootthira@gmail.com as a Super Admin in users table by matching auth.users email
UPDATE users 
SET is_super_admin = true 
WHERE id = (SELECT id::text FROM auth.users WHERE email = 'whootthira@gmail.com' LIMIT 1);

-- 6. Enable Row Level Security (RLS) on group_simulations
ALTER TABLE group_simulations ENABLE ROW LEVEL SECURITY;

-- 7. Create tenant isolation policy supporting Super Admin global checks and Org Admin EXISTS checks
DROP POLICY IF EXISTS org_isolation_with_super_admin_policy ON group_simulations;

CREATE POLICY org_isolation_with_super_admin_policy ON group_simulations
  FOR ALL
  USING (
    -- Condition 1: If caller is global Super Admin, grant immediate access
    (SELECT is_super_admin FROM users WHERE id = auth.uid()::text) = true
    OR
    -- Condition 2: If caller is Org Admin, verify membership matching organization via exists index scan
    EXISTS (
      SELECT 1 FROM org_members 
      WHERE org_members.org_id = group_simulations.org_id 
        AND org_members.user_id = auth.uid()::text 
        AND org_members.role = 'admin'
    )
  );

COMMENT ON TABLE group_simulations IS 'Stores logs of simulated groups, synergy scores, and manager recommendations.';
